# Generated by Django 5.2.12 on 2026-04-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_emails',
            field=models.IntegerField(default=0),
        ),
    ]
