# Generated by Django 5.2.12 on 2026-04-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_reset_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_reset_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
