# Generated by Django 5.2.11 on 2026-03-13 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_reservation_guests_alter_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[(810, '810'), (910, '910'), (1108, '1108'), (1109, '1109')], max_length=20)),
                ('vendor', models.CharField(choices=[('vrbo', 'VRBO')], max_length=20)),
                ('url', models.URLField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.customer'),
        ),
    ]
