# Generated by Django 5.2.12 on 2026-04-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='ctype',
            field=models.TextField(choices=[('pool', 'Pool'), ('pickleball', 'Pickleball'), ('entry', 'Door Entry')]),
        ),
    ]
