# Generated by Django 5.2.12 on 2026-04-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_alter_codes_ctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='code',
        ),
    ]
