# Generated by Django 5.2.11 on 2026-03-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_units_alter_reservation_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
