# Generated by Django 5.2.12 on 2026-04-18 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_remove_codes_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codes',
            name='ctype',
            field=models.TextField(choices=[('pool', 'Pool'), ('pickleball', 'Pickleball'), ('entry', 'Door Entry'), ('wifi-ssid', 'WiFi SSID'), ('wifi-password', 'WiFi Password'), ('checkin-checkout', 'Check-in/Check-out instructions')]),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
