# Generated by Django 5.2.11 on 2026-03-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_reservation_notes_reservation_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='uid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
    # mo added it due to a manual operation
    operations = []
