# Generated by Django 5.2.11 on 2026-03-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_remove_reservation_id_alter_reservation_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='sleeps',
            field=models.IntegerField(default=6),
        ),
    ]
