# Generated by Django 5.2.12 on 2026-04-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_reservation_customer_to_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
