# Generated by Django 5.2.12 on 2026-04-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='property_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
